version: "3.1"

services:  
  db:
    image: postgis/postgis:12-master
    container_name: stafdbs_db
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
       POSTGRES_PASSWORD: postgres
       POSTGRES_USER: postgres
       POSTGRES_DB: stafdbs
  adminer:
    image: adminer:4.7.7
    ports:
      - 8080:8080
    container_name: stafdbs_adminer
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: stafdbs_web
